[[redirects]]
  from = "/index"
  to = "/"
  status = 301

[[redirects]]
  from = "/portfolio"
  to = "/portfolio.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/expertise"
  to = "/expertise.html"
  status = 200
